### ISSUE TITLE
Placing the map inside a listener dataview doesn't update the map properly

### ISSUE THREAD

**Issue by Gmanicus** [ivosturm/GoogleMapsCustomMarkerReact#4]
I've been wracking my brain trying to get the default Maps widget to work in this way, as well as this widget. Unfortunately, it seems this may be commonality between them.

In our project, we have a list of addresses. Upon selecting one, an Address dataview is updated which holds the Google Maps Custom Marker widget. However, the map looks like this when an address is selected:

![image](https://user-images.githubusercontent.com/11013079/140795458-243f7575-6f79-4c35-be0f-0d3054c2881d.png)

This is how the setup looks in Mendix:

![image](https://user-images.githubusercontent.com/11013079/140795803-69973373-f2a9-4176-8e79-4938677522be.png)
![image](https://user-images.githubusercontent.com/11013079/140795845-32e365c3-2f28-4e6e-9ba9-020c7b47d00b.png)

**Comment by ivosturm** [comment]
Hi Grant,

How have you been setting up the data source of the widget? Is the entity already stored in the database?

I think I tested this scenario as well and what I did there was populate the data source of my widget with nanoflow. In the nanoflow I retrieve the object based on the Current Object variable.

If you can add me to the/a test project I am happy to check it for you.

From: Grant Scrits ***@***.***>
Sent: Monday, November 8, 2021 7:15 PM
To: ivosturm/GoogleMapsCustomMarkerReact ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ivosturm/GoogleMapsCustomMarkerReact] Placing the map inside a listener dataview doesn't update the map properly (Issue #4)


I've been wracking my brain trying to get the default Maps widget to work in this way, as well as this widget. Unfortunately, it seems this may be commonality between them.

In our project, we have a list of addresses. Upon selecting one, an Address dataview is updated which holds the Google Maps Custom Marker widget. However, the map looks like this when an address is selected:

[image]<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F11013079%2F140795458-243f7575-6f79-4c35-be0f-0d3054c2881d.png&data=04%7C01%7Civo.sturm%40valcon.com%7Ce97a9bd3169141a852e508d9a2e3b1a4%7Cf854fda6184f4f40a5e283a4f8924a15%7C0%7C0%7C637719921094998721%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=tGVNGM4MposzOIWE6c%2BjtHrEjIzeLTQUAZT324qY20Y%3D&reserved=0>

This is how the setup looks in Mendix:

[image]<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F11013079%2F140795803-69973373-f2a9-4176-8e79-4938677522be.png&data=04%7C01%7Civo.sturm%40valcon.com%7Ce97a9bd3169141a852e508d9a2e3b1a4%7Cf854fda6184f4f40a5e283a4f8924a15%7C0%7C0%7C637719921094998721%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=dPAfQKca5ouPXmpqLkCicsocDznKo039WlVsBW5P0V0%3D&reserved=0>
[image]<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F11013079%2F140795845-32e365c3-2f28-4e6e-9ba9-020c7b47d00b.png&data=04%7C01%7Civo.sturm%40valcon.com%7Ce97a9bd3169141a852e508d9a2e3b1a4%7Cf854fda6184f4f40a5e283a4f8924a15%7C0%7C0%7C637719921095008720%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=nbzRqSueiaawmf06UUiTCF3R%2F%2FTSUrm2Hf1n4BV91CE%3D&reserved=0>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fivosturm%2FGoogleMapsCustomMarkerReact%2Fissues%2F4&data=04%7C01%7Civo.sturm%40valcon.com%7Ce97a9bd3169141a852e508d9a2e3b1a4%7Cf854fda6184f4f40a5e283a4f8924a15%7C0%7C0%7C637719921095008720%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=15xnetzSBPLg3%2FSsJ6Bu1yOnyE6wg2xi6Ienbd78o3A%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADLGJWW6FVONTLVE3RFJPO3ULAHSRANCNFSM5HTKIROA&data=04%7C01%7Civo.sturm%40valcon.com%7Ce97a9bd3169141a852e508d9a2e3b1a4%7Cf854fda6184f4f40a5e283a4f8924a15%7C0%7C0%7C637719921095018705%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=4SRUZSBEI2rlHuJ20VDKTzbzbMZOvcoEBKtJlchHcSo%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Civo.sturm%40valcon.com%7Ce97a9bd3169141a852e508d9a2e3b1a4%7Cf854fda6184f4f40a5e283a4f8924a15%7C0%7C0%7C637719921095018705%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=CzlaaZz%2BmiLwqcC9Pp%2Bec7Fzmzin8BdJA9Oh%2FXyDqoU%3D&reserved=0> or Android<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Civo.sturm%40valcon.com%7Ce97a9bd3169141a852e508d9a2e3b1a4%7Cf854fda6184f4f40a5e283a4f8924a15%7C0%7C0%7C637719921095028701%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=N0NDkdt3waoq6IKYN97mfbP1NTd6FiJua%2Bmqa4BCpnw%3D&reserved=0>.


Disclaimer:
This e-mail and any files attached to it are confidential and only intended to be used by the recipient(s). If you receive this e-mail by error, please return it to Valcon without producing, distributing or retaining copies hereof.

**Comment by Gmanicus** [comment]
Turns out, we had the Latitude and Longitude reversed in our test data. That ended up being the issue. The map _is_ updating properly, I just couldn't see it because it was trying to mark a point outside the bounds of the Earth.

So sorry about that! Thanks for creating this widget.

If others read this and are curious what the answer to Ivostrum's question is: I'm using a microflow which is being passed the Address as a parameter, adding that to a new list, and then returning that list to the map widget. This way I can show only that address and satisfy the datasource's need for a list.

**Comment by ivosturm** [comment]
Great and not a problem! If you could add a review that would be great, thanks!
________________________________
Van: Grant Scrits ***@***.***>
Verzonden: Thursday, November 11, 2021 6:41:27 AM
Aan: ivosturm/GoogleMapsCustomMarkerReact ***@***.***>
CC: Ivo Sturm ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [ivosturm/GoogleMapsCustomMarkerReact] Placing the map inside a listener dataview doesn't update the map properly (Issue #4)


Turns out, we had the Latitude and Longitude reversed in our test data. That turned out to be the issue. The map is updating properly. I just couldn't see it before.

So sorry about that! Thanks for creating this widget.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fivosturm%2FGoogleMapsCustomMarkerReact%2Fissues%2F4%23issuecomment-966006201&data=04%7C01%7Civo.sturm%40firsttechnology.nl%7Ccd09afed0f8749c69a3308d9a4d5e885%7C69c61094d320414582709c50ccbd08ab%7C0%7C0%7C637722060922339468%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=2gQj%2B8k6BbXJUDHjlVzRw4BkLxphrAGKBsKQNrU1hWI%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADLGJWWGCIKIQOXORRO2XDTULNJQPANCNFSM5HTKIROA&data=04%7C01%7Civo.sturm%40firsttechnology.nl%7Ccd09afed0f8749c69a3308d9a4d5e885%7C69c61094d320414582709c50ccbd08ab%7C0%7C0%7C637722060922339468%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=aAqcGwNjHLneZUVfyWwcz9sA00GuSC617VUEa4AZLrg%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Civo.sturm%40firsttechnology.nl%7Ccd09afed0f8749c69a3308d9a4d5e885%7C69c61094d320414582709c50ccbd08ab%7C0%7C0%7C637722060922349415%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ERET8q5kcu9sCJYmr2EI66r3%2Fs%2F%2FPFKUNfWjd%2BNtoq4%3D&reserved=0> or Android<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Civo.sturm%40firsttechnology.nl%7Ccd09afed0f8749c69a3308d9a4d5e885%7C69c61094d320414582709c50ccbd08ab%7C0%7C0%7C637722060922349415%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=6wSrKSjj6cOyU%2BTsF%2B5tI%2FbdJRAVs7AsWmYrbrVsRrA%3D&reserved=0>.
